executor:
  - name: VALIDATE
    procedure:
      - type: MODULE_EXECUTOR
        source: REQUEST_PROCESSING.GET_REQUEST # moduleName.[executor|mapping].name
      - type: JSON_SCHEMA_VALIDATION
        source: >-
          {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "$id": "https://example.com/request.schema.json",
            "title": "Request",
            "description": "A request from Acme's catalog",
            "type": "object",
            "properties": {
              "requestId": {
                "description": "The unique identifier for a request",
                "type": "integer"
              },
              "requestName": {
                "description": "Name of the request",
                "type": "string"
              }
            }
          }
      - type: MODULE_EXECUTOR
        source: REQUEST_PROCESSING.GET_ITEMS
      - type: JSON_SCHEMA_VALIDATION
        source: >-
          {
            "$schema": "https://json-schema.org/draft/2020-12/schema",
            "$id": "https://example.com/product.schema.json",
            "title": "Product",
            "description": "A product from Acme's catalog",
            "type": "object",
            "properties": {
              "productId": {
                "description": "The unique identifier for a product",
                "type": "integer"
              },
              "productName": {
                "description": "Name of the product",
                "type": "string"
              }
            }
          }
